<a href="https://colab.research.google.com/github/rakshitakanwar/day1.ipynb/blob/main/day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#filter
import numpy as np
arr= np.array([10,20,3,4,90,200])
arr_f= arr[arr>20]
print(arr_f)

[ 90 200]


In [ ]:
import numpy as np
arr= np.array([10,20,30,6,3,2])
arr_f= arr[arr!=6]
print(arr_f)

[10 20 30  3  2]


In [ ]:
import numpy as np
arr = np.array([10,20,30,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[15 18]


In [ ]:
#fancy indexing
import numpy as np
arr= np.array([10,20,30,4,90,100])
print(arr)
arr_f= arr[[0,2]] #0 index value and 2 index value
print(arr_f)

[ 10  20  30   4  90 100]
[10 30]


In [ ]:
#where
import numpy as np
arr= np.array([10,20,3,4,90,100])
print(arr)
arr_w= np.where(arr>9,"True","False")
print(arr_w)

[ 10  20   3   4  90 100]
['True' 'True' 'False' 'False' 'True' 'True']


In [ ]:
import numpy as np
arr = np.array([10,20,3,4,90,100])
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)

[ 12  22   5   6  92 102]


In [ ]:
#Adding and Removing Data
#concatenate
#1d
import numpy as np
arr= np.array([10,20,30])
arr1= np.array([1,2,3])
#concatenate
arr_arr1=np.concatenate((arr,arr1))
print(arr_arr1)

[10 20 30  1  2  3]


In [ ]:
#2d
import numpy as np
arr = np.array([[10,20],[30,40]])
arr1 = np.array([[1,2],[3,4]])
arr_arr1= np.concatenate((arr, arr1),axis=1) #axis=1 for column, axis=0 for row
print(arr_arr1)

[[10 20  1  2]
 [30 40  3  4]]


In [ ]:
#vstack=> vertically join (row wise)
import numpy as np
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
result= np.vstack((arr,arr1))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
#hstack=>horizontally join(column wise)
arr = np.array([10,20,30])
arr1 = np.array([40,50,60])
result= np.hstack((arr,arr1))
print(result)

[10 20 30 40 50 60]


In [ ]:
#2d
#vstack
import numpy as np
arr = np.array([[1,2],[3,4]])
arr1 = np.array([[5,6],[7,8]])
result = np.vstack((arr, arr1))
print(result)
#hstack
import numpy as np
arr = np.array([[10,20],[30,40]])
arr1 = np.array([[50,60],[70,80]])
result1 = np.hstack((arr, arr1))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[10 20 50 60]
 [30 40 70 80]]


1. np.sum(a) -> Sum of all elements
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.median(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
11. np.argmin(a) -> Index position of minimum value
12. np.argmax(a) -> Index position of maximum value
13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a) -> Returns unique values only -> Removes duplicates
15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
17. np.ptp(a) -> Range = Max - Min
18. np.any(a) -> True if at least one value is True



In [ ]:
#1-d
import numpy as np
arr = np.array([2,4,5,6,7])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.std(arr))
print(np.prod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.abs(arr))
print(np.unique(arr))
print(np.percentile(arr,50))
print(np.quantile(arr,0.5))
print(np.ptp(arr))
print(np.any(arr))

24
4.8
5.0
2
7
2.96
1.7204650534085253
1680
[ 2  6 11 17 24]
[   2    8   40  240 1680]
0
4
[2 4 5 6 7]
[2 4 5 6 7]
5.0
5.0
5
True


Handling Missing Values=> find out where is missing values



In [ ]:
#nan=>not a number(null)
import numpy as np
arr= np.array([10,20,np.nan,40])
print(arr)
#isnan
print(np.isnan(arr))
#update by number
new_arr= np.nan_to_num(arr, nan=10)
print(new_arr)

[10. 20. nan 40.]
[False False  True False]
[10. 20. 10. 40.]


In [ ]:
import numpy as np
# data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
# 1. Print complete dataset
print("Dataset:")
print(sales_data)
# 2. Shape of array
print("Shape:", sales_data.shape)
# 3. Number of dimensions
print("Dimensions:", sales_data.ndim)
# 4. Total number of elements
print("Total Elements:", sales_data.size)
# 5. Only Restaurant IDs
print("\nRestaurant IDs:")
print(sales_data[:, 0])
# 6. 2021 sales data
print("\n2021 Sales:")
print(sales_data[:, 1])
# 7. 2024 sales data
print("\n2024 Sales:")
print(sales_data[:, 4])
# 8. Maximum sales value
print("\nMaximum Sales Value:", np.max(sales_data[:, 1:]))
# 9. Minimum sales value
print("Minimum Sales Value:", np.min(sales_data[:, 1:]))
# 10. Total sales of all restaurants in 2021
print("\nTotal Sales in 2021:", np.sum(sales_data[:, 1]))
# 11. Average sales in 2024
print("Average Sales in 2024:", np.mean(sales_data[:, 4]))
# 12. Total sales of each restaurant (2021-2024)
print("\nTotal Sales of Each Restaurant:")
print(np.sum(sales_data[:, 1:], axis=1))
# 13. Average sales of each restaurant (2021-2024)
print("\nAverage Sales of Each Restaurant:")
print(np.mean(sales_data[:, 1:], axis=1))

Dataset:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
Shape: (5, 5)
Dimensions: 2
Total Elements: 25

Restaurant IDs:
[1 2 3 4 5]

2021 Sales:
[150000 120000 200000 180000 160000]

2024 Sales:
[250000 190000 300000 270000 230000]

Maximum Sales Value: 300000
Minimum Sales Value: 120000

Total Sales in 2021: 810000
Average Sales in 2024: 248000.0

Total Sales of Each Restaurant:
[800000 610000 990000 900000 780000]

Average Sales of Each Restaurant:
[200000. 152500. 247500. 225000. 195000.]
