<a href="https://colab.research.google.com/github/rakshitakanwar/day1.ipynb/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#3D
arr= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.ndim)
print(arr[0]) #block
print(arr[0,0])#block ki row
print(arr[0,0,0])#block ki row ka column
print(arr[:,0])#all block
print(arr[:,:,0]) #all block=> all rows=> 0 column

3
[[1 2]
 [3 4]]
[1 2]
1
[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [ ]:
#for loop in numoy
#1d
import numpy as np
arr= np.array([10,20,30])
print(arr)
for i in arr:
  print(i)

[10 20 30]
10
20
30


In [ ]:
#2d
import numpy as np
arr= np.array([[1,2],[3,4],[5,6]])
print(arr)
for i in arr:
  for j in i:
    print(j)

[[1 2]
 [3 4]
 [5 6]]
1
2
3
4
5
6


In [ ]:
#3d
import numpy as np
arr= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
for i in arr:
  for j in i:
    for k in j:
      print(k)
#for i in np.nditer(arr):
  #print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [ ]:
#while and using np.nditer

In [ ]:
#sorting
#sort for 1d
import numpy as np
arr= np.array([10,35,40,7,15,20])
print(np.sort(arr)) #ascending
print(np.sort(arr)[::-1]) #descending

[ 7 10 15 20 35 40]
[40 35 20 15 10  7]


In [ ]:
import numpy as np
arr= np.array([10,35,40,7,15,20])
arr1= arr.reshape(2,3)
print(arr1)
print(np.sort(arr1)) #ascending

[[10 35 40]
 [ 7 15 20]]
[[10 35 40]
 [ 7 15 20]]


In [ ]:
#filter
#1d
import numpy as np
arr= np.array([10,20,30,40])
print(arr[arr>30])
print(arr[0]+arr[1])

[40]
30


In [ ]:
#where
import numpy as np
arr= np.array([10,20,30,40])
print(np.where(arr>20),"true","false")
print(np.where(arr>20, 2*arr,arr))

(array([2, 3]),) true false
[10 20 60 80]
