<a href="https://colab.research.google.com/github/rakshitakanwar/day1.ipynb/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy | list
import numpy as np
import time

start= time.time()
sum1=0
for i in range(1000000):
  sum1+=i*2
end= time.time()
print("for list",sum1, end-start)

#for numpy| array (array work every element | element wise)
start1= time.time()
sum2=0
arr= np.array(1000000)*2
sum2= arr.sum()
endl= time.time()
print("for array",sum2, endl-start1)


for list 999999000000 0.16076397895812988
for array 2000000 0.0003662109375


In [3]:
import time as t
print(t.time())

1781857890.6293414


In [5]:
#zeros
import numpy as np
arr= np.zeros(5)
print(arr)
#2D
arr1= np.zeros((2,3))  #2 rows and 3 column
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#ones
import numpy as np
#arr 1d
arr= np.ones(5)
print(arr)

#2d
arr1= np.ones((2,3))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#full
import numpy as np
#1d
arr= np.full((5),7)
print(arr)

#2d
arr1= np.full((2,3),7)
print(arr1)

[7 7 7 7 7]
[[7 7 7]
 [7 7 7]]


In [14]:
#shape
#1D
arr= np.zeros(6)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
#2D
arr= np.zeros((3,2))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[0. 0. 0. 0. 0. 0.]
(6,)
1
6
float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


In [15]:
#1d
arr= np.full((5),7)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


#2d
arr1= np.full((2,3),7)
print(arr1)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[7 7 7 7 7]
(5,)
1
5
int64
[[7 7 7]
 [7 7 7]]
(5,)
1
5
int64


In [26]:
#Reshape
#1D array
import numpy as np
arr= np.arange(6)
print(arr)

#2D array
import numpy as np
arr1= arr.reshape(2,3) # 2 rows and  3column
print(arr1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [28]:
#flatten
import numpy as np
#2D
arr= np.arange(6)
arr1= arr.reshape(2,3)
print(arr1)

#flatten
print(arr1.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [32]:
#ravel
import numpy as np
#2D
arr1= np.arange(6).reshape(2,3)
print(arr1)

#ravel
print(arr.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [35]:
#ravel
import numpy as np
#2D
arr1= np.arange(6).reshape(2,3)
print(arr1)
#flatten  => copy
arr_new= arr1.flatten()
arr_new[0]=100
print(arr1)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [36]:
#ravel => original ke andar hi changes ho jate hai
import numpy as np
#2D
arr1= np.arange(9).reshape(3,3)
print(arr1)
#ravel
arr_new1= arr1.ravel()
arr_new1[0]=100
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


In [37]:
#Transpose
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

#transpose
arr1= arr.transpose()
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
